version: "3.7"
services:
  mycart-frontend:
    build:
      context: ./frontend
    image: rajendra1337/mycart-frontend:3.0
    depends_on: 
      - mycart-backend
    environment:
      BACKENDLB: mycart-backend
    ports:
      - "9000:80"
    volumes:
      - type: volume
        source: mycart-frontend-logvol
        target: /var/log
  mycart-backend:
    build:
      context: ./backend
    image: rajendra1337/mycart-backend:3.0
    volumes:
      - type: volume
        source: mycart-backend-logvol
        target: /var/log
  mycart-db:
    image: mysql:5.7
    volumes:
      - type: volume
        source: mycart-db-logvol
        target: /var/lib/mysql        
volumes:
  mycart-frontend-logvol:
  mycart-backend-logvol:
  mycart-db-logvol: